"""
Hybrid LLM interface.

Priority:
  1. Groq (llama-3.1-8b-instant by default) via GROQ_API_KEY
  2. OpenAI GPT-4o-mini via OPENAI_API_KEY
  3. Anthropic Claude Haiku via ANTHROPIC_API_KEY
  4. Deterministic rule-based fallback (no credentials)
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from src.config import (
    GROQ_API_KEY,
    GROQ_MODEL,
    OPENAI_API_KEY,
    ANTHROPIC_API_KEY,
)


SYSTEM_PROMPT = (
    "You are TPO Sentinel, an expert healthcare payment-integrity investigator "
    "at Cotiviti. You reason step-by-step using clinical and claims data to "
    "produce clear, evidence-cited recommendations. Be concise and professional."
)


def _call_groq(prompt: str) -> str:
    from openai import OpenAI

    client = OpenAI(
        api_key=GROQ_API_KEY,
        base_url="https://api.groq.com/openai/v1",
    )
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        temperature=0.2,
        max_tokens=800,
    )
    return response.choices[0].message.content or ""


def _call_openai(prompt: str) -> str:
    from openai import OpenAI

    client = OpenAI(api_key=OPENAI_API_KEY)
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        temperature=0.2,
        max_tokens=800,
    )
    return response.choices[0].message.content or ""


def _call_anthropic(prompt: str) -> str:
    import anthropic

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    message = client.messages.create(
        model="claude-3-haiku-20240307",
        max_tokens=800,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text


def _fallback(prompt: str) -> str:
    """
    Deterministic template-based response.  Parses structured cues that
    agent.py embeds in the prompt so the output is still meaningful.
    """
    lines = prompt.split("\n")
    context: dict = {}
    for line in lines:
        if "fraud_probability:" in line:
            try:
                context["fraud_prob"] = float(line.split(":")[-1].strip())
            except ValueError:
                pass
        if "anomaly_months:" in line:
            try:
                context["anomaly_months"] = int(line.split(":")[-1].strip())
            except ValueError:
                pass
        if "outlier_flag:" in line:
            context["outlier"] = "true" in line.lower()
        if "top_features:" in line:
            context["features"] = line.split(":", 1)[-1].strip()

    fraud_prob = context.get("fraud_prob", 0.5)
    anomaly_months = context.get("anomaly_months", 0)
    outlier = context.get("outlier", False)
    features = context.get("features", "high claim volume, billing irregularities")

    if fraud_prob >= 0.75:
        recommendation = "DENY / AUDIT"
        rationale = (
            f"The fraud probability of {fraud_prob:.0%} far exceeds the 75 % audit threshold. "
        )
    elif fraud_prob >= 0.5:
        recommendation = "REVIEW"
        rationale = (
            f"The fraud probability of {fraud_prob:.0%} exceeds the 50 % review threshold. "
        )
    else:
        recommendation = "PAY"
        rationale = (
            f"The fraud probability of {fraud_prob:.0%} is below the review threshold. "
        )

    anomaly_note = (
        f"Time-series analysis flagged {anomaly_months} anomalous billing month(s). "
        if anomaly_months > 0 else "No billing-volume anomalies detected. "
    )
    outlier_note = (
        "Provider is a statistical outlier relative to its peer cluster — "
        "peer-group benchmarking supports further scrutiny. "
        if outlier else "Provider billing patterns align with peer cohort norms. "
    )

    return (
        f"**Recommendation: {recommendation}**\n\n"
        f"{rationale}"
        f"{anomaly_note}"
        f"{outlier_note}\n\n"
        f"**Key drivers:** {features}\n\n"
        f"*Generated by TPO Sentinel rule-based fallback (no LLM key configured).*"
    )


def generate(prompt: str) -> tuple[str, str]:
    """
    Returns (response_text, source) where source is one of:
      "groq", "openai", "anthropic", "fallback"
    """
    if GROQ_API_KEY:
        try:
            return _call_groq(prompt), "groq"
        except Exception as e:
            print(f"[llm] Groq failed: {e}. Trying OpenAI…")

    if OPENAI_API_KEY:
        try:
            return _call_openai(prompt), "openai"
        except Exception as e:
            print(f"[llm] OpenAI failed: {e}. Trying Anthropic…")

    if ANTHROPIC_API_KEY:
        try:
            return _call_anthropic(prompt), "anthropic"
        except Exception as e:
            print(f"[llm] Anthropic failed: {e}. Using fallback…")

    return _fallback(prompt), "fallback"
